#!/usr/bin/env ruby

$LOAD_PATH << "#{ENV['PACKMAN_ROOT']}/framework"
$LOAD_PATH << "#{ENV['PACKMAN_ROOT']}/packages"
require 'packman_framework'
require 'packman_packages'

case ARGV[0]
    when 'collect'
      PACKMAN::ConfigManager.parse(ARGV[1])
      PACKMAN.collect_packages
    when 'install'
      PACKMAN::ConfigManager.parse(ARGV[1])
      PACKMAN.install_packages
    when 'switch'
      PACKMAN::ConfigManager.parse(ARGV[1])
      PACKMAN.switch_packages
    when 'update'
      saved_dir = FileUtils.pwd
      FileUtils.chdir ENV['PACKMAN_ROOT']
      system 'git pull'
      FileUtils.chdir saved_dir
    when 'help'
      
    else
      PACKMAN.report_error "Unknown command #{ARGV[0]}!"
end
