#!/usr/bin/env ruby

if not ENV.has_key? 'PACKMAN_ROOT'
  print "[Error]: #{File.expand_path(File.dirname(__FILE__))}/setup.sh is not sourced!\n"
  exit
end

$LOAD_PATH << "#{ENV['PACKMAN_ROOT']}/framework"
$LOAD_PATH << "#{ENV['PACKMAN_ROOT']}/packages"
require 'packman_framework'

case PACKMAN::CommandLine.subcommand
when :config
  PACKMAN.edit_config_file
when :collect
  PACKMAN.collect_packages
when :install
  PACKMAN.install_packages
when :remove
  PACKMAN.remove_packages
when :switch
  PACKMAN.switch_packages
when :mirror
  PACKMAN.mirror_packages
when :update
  PACKMAN.update
when :help
  PACKMAN::CommandLine.print_usage
when :report
  PACKMAN.report
else
  PACKMAN::CLI.report_error "Unknown subcommand #{PACKMAN::CommandLine.subcommand}!"
end
